# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20160927_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(upload_to='school/images'),
        ),
    ]
